baseURL = "https://hexoctal.github.io/"
languageCode = "en-us"
title = "HexOctal"

# Code Highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true

paginate = 7
[permalinks]
    journal = "/:year/:month/:title"
[taxonomies]
    tag = "tags"
    category = "categories"
